### ISSUE TITLE
不要造轮子了, brew install mackup

### ISSUE THREAD

**Issue by leecade** [jcouyang/dotfiles#1]

**Comment by jcouyang** [comment]
...这个确实可以满足大多数人的需求

不过光扫了一眼这个mackup 这个[配置](https://github.com/lra/mackup/blob/master/mackup/applications/emacs.cfg)就决心还是必须用自己的轮子更安全
1. 我的 emacs 配置文件并不是 `.emacs` 而是 `init.el` 和 `config.org`
2. 除此之外其他文件我都不想 sync，为什么要帮我 sync 整个 `.emacs.d` 目录，万一我有密码/token 在 `.emacs.d/user.el` 呢。

**Comment by jcouyang** [comment]
https://github.com/jcouyang/dotfiles#-sensitive-dotfiles
