### ISSUE TITLE
git-remote-gcrypt might report a repository as "not found" 

### ISSUE THREAD

**Issue by zwkcoding** [jcouyang/dotfiles#2]
> git-remote-gcrypt might report a repository as "not found" when the repository does in fact exist, but git-remote-gcrypt is having authentication, port, or network connectivity issues.

refer to  https://github.com/spwhitton/git-remote-gcrypt#known-issues

我试了很久。。。。然后发现。。。。

**Comment by xiaoyvr** [comment]
我尝试了很久，然后就work了啊！～
```bash
git remote -v                                                                                                             03:10:20
origin	gcrypt::git@github.com:blabla/dotfiles.git (fetch)
origin	gcrypt::git@github.com:blabla/dotfiles.git (push)
```
需要先添加另一个remote，不要和origin重名，然后用 `git remote set-url` 把origin的改过来后删掉那个多余的remote，就ok了
